trigger:
- main

jobs:
- job: 'RunMATLABBuild'

  pool:
    vmImage: $(PLATFORM)
  strategy:
    matrix:            
      windows-MATLAB-latest-including-prerelease:
        PLATFORM: 'windows-latest'
        MATLAB_RELEASE: latest-including-prerelease
      linux-MATLAB-latest-including-prerelease:
        PLATFORM: 'ubuntu-latest'
        MATLAB_RELEASE: latest-including-prerelease
      mac-MATLAB-latest-including-prerelease:
        PLATFORM: 'macOS-latest'
        MATLAB_RELEASE: latest-including-prerelease

  steps:
  - task: InstallMATLAB@1
    inputs:
      release: $(MATLAB_RELEASE)
      products: >
        MATLAB
  # This task Runs all the MATLAB and Simulink tests and generate variety of test artifacts. Check the documentation for all supported task parameters.
  - task: RunMATLABCommand@1
    inputs:
      command: ver
