trigger:
- main
    
jobs:
- job: 'RunMATLABBuild'
 
  pool:
    vmImage: $(PLATFORM)

  strategy:
    matrix:    
      windows-MATLAB-R2023a:
        PLATFORM: 'windows-latest'
        MATLAB_RELEASE: R2023a
      linux-MATLAB-R2023a:
        PLATFORM: 'ubuntu-latest'
        MATLAB_RELEASE: R2023a
      mac-MATLAB-R2023a:
        PLATFORM: 'macOS-latest'
        MATLAB_RELEASE: R2023a
        
      windows-MATLAB-R2024a:
        PLATFORM: 'windows-latest'
        MATLAB_RELEASE: R2024a
      linux-MATLAB-R2024a:
        PLATFORM: 'ubuntu-latest'
        MATLAB_RELEASE: R2024a
      mac-MATLAB-R2024a:
        PLATFORM: 'macOS-latest'
        MATLAB_RELEASE: R2024a
 
  steps:
  - task: Cache@2
    inputs:
      key: MATLAB-$(MATLAB_RELEASE)-$(PLATFORM)-20240329c
      path: $(AGENT_TOOLSDIRECTORY)/MATLAB
  - task: InstallMATLAB@1
    inputs:
      release: $(MATLAB_RELEASE)
      products: >
        MATLAB
        MATLAB_Compiler
        MATLAB_Compiler_SDK
        MATLAB_Test
  # This task Runs all the MATLAB and Simulink tests and generate variety of test artifacts. Check the documentation for all supported task parameters.
  - task: RunMATLABCommand@1
    inputs:
      command: ver
       
