jobs:
  - job: build
    strategy:
      matrix:
        linux:
          vmImage: ubuntu-22.04
        macos:
          vmImage: macOS-latest
        windows:
          vmImage: windows-latest
    steps:
    - task: InstallMATLAB@1
    - task: RunMATLABBuild@1
      inputs:
        tasks: test