version: '2.1'
orbs:
  node: circleci/node@1.0.0
jobs:
  issue-warning:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - name: issue-warning
        run: |
          YELLOW='\033[1;33m'
          NC='\033[0m' # No Color
          echo -e "${YELLOW}WARNING: This version of setup-matlab is deprecated. Please upgrade!${NC}"
workflows:
  test_my_app:
    jobs:
      - issue-warning

