version: '2.1'
orbs:
  node: circleci/node@1.0.0
jobs:
  install-node-example:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install
      - run: node --version
workflows:
  test_my_app:
    jobs:
      - install-node-example

