version: '2.1'
jobs:
  issue-warning:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: issue-warning
          command: |
            YELLOW='\033[1;33m'
            NC='\033[0m' # No Color
            echo -e "${YELLOW}WARNING: This version of setup-matlab is deprecated. Please upgrade!${NC}"
workflows:
  test_my_app:
    jobs:
      - issue-warning

