version: '2.1'
orbs:
  matlab: mathworks/matlab@0

executors:
  linux: # a Linux VM running Ubuntu 20.04 
    machine:
      image: ubuntu-2204:2024.01.1
  macos: # macos executor running Xcode
    macos:
      xcode: 15.1.0
    resource_class: macos.x86.medium.gen2
  windows:
    win/default
jobs:
  issue-warning:
    environment:
      MATHWORKS_INSTALLER_BASE_URL: "https://mpmtest.s3.amazonaws.com"
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - matlab/install
      - matlab/run-command:
          command: ver
workflows:
  test_my_app:
    jobs:
      - issue-warning:
          matrix:
            parameters:
              os: [linux, macos, windows]
