version: '2.1'
orbs:
  matlab: mathworks/matlab@0
jobs:
  issue-warning:
    environment:
      MATHWORKS_INSTALLER_BASE_URL: "https://mpmtest.s3.amazonaws.com"
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - matlab/install
      - matlab/run-command:
          command: ver
workflows:
  test_my_app:
    jobs:
      - issue-warning

