version: '2.1'
orbs:
  matlab: mathworks/matlab@1  
jobs:
  build:
    docker:
      - image: debian:11
    steps:
      - checkout
      - matlab/install
      - matlab/run-build:
          tasks: test