on: [push]
jobs:
  build:
    name: Run MATLAB Build
    runs-on: ubuntu-latest
    container:
      image: debian:11
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - run: apt-get update && apt-get install -y curl sudo
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
      - name: Run build
        uses: matlab-actions/run-build@v2
        with:
          tasks: test
