name: Run MATLAB Tests on GitHub-Hosted Runner

on: # yamllint disable-line rule:truthy
  push:
jobs:
  run-tests:
    name: MATLAB Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: yayayaya
        run: echo "##[warning]This version of setup-matlab is deprecated. Please upgrade!" 
