on: [push]
jobs:
  build:
    name: Run MATLAB Build
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Cache MATLAB
        id: cache-matlab
        uses: actions/cache@v4
        with:
          path: ${{ runner.tool_cache }}/MATLAB
          key: ${{ matrix.os }}-${{ matrix.release }}
      - run: |
          echo "C:"
          ls C:\hostedtoolcache\windows\MATLAB\2023.2.999\x64
          echo "D:"
          ls D:\hostedtoolcache\windows\MATLAB\2023.2.999\x64
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        continue-on-error: true
      - run: |
          echo "C:"
          ls C:\hostedtoolcache\windows\MATLAB\2023.2.999\x64
          echo "D:"
          ls D:\hostedtoolcache\windows\MATLAB\2023.2.999\x64
