on: [push]
jobs:
  build:
    name: Run MATLAB Build
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
      - name: Run build
        uses: matlab-actions/run-tests@v2
        with:
          code-coverage-cobertura: code-coverage/coverage.xml
