name: Run MATLAB Tests on GitHub-Hosted Runner

on: # yamllint disable-line rule:truthy
  push:
jobs:
  run-tests:
    name: Checkout, Compile and Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - run: echo "##[warning]This version of setup-matlab is deprecated. Please upgrade!" 
